config/routes.rb
Konsilo::Application.routes.draw do
  resources :alerts

  root to: "home#index"

  devise_for :user, controllers: {registrations: 'registrations'}do
    get "/login", :to => "devise/sessions#new"
    destroy "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "devise/registrations#new"
  end

  resources :alerts do
    member do
      put "like", to: "alerts#like"
      put "dislike", to: "alerts#dislike"
      get "add_tag", to: "alerts#add_tag"
      put "update_tags", to: "alerts#update_tags"
    end
  end

end

app/views/shared/_alert.html.erb
<ul class="list-group list-alerts">
  <li class="list-group-item" id="alert-<%=alert.id%>">
    <h4 class="list-group-item-heading">
      <%= alert.title.blank? ? t(:twitter_message) : alert.title %>

      <span class="label label-<%= alert.ranking_score < 0 ? "danger" : "success" %>">
        <%= "%.2f" % alert.ranking_score %>
      </span>
    </h4>

    <span class="badge votes">
      <span class="label label-success">
        <%= link_to "+1", like_alert_path(alert), method: :put, remote: true, class: 'like_alert alert-link' %>
      </span>
      <span class="btn likes">
        <%= alert.likes.size %>
      </span>

      <span class="label label-danger">
        <%= link_to "-1", dislike_alert_path(alert), method: :put, remote: true, class: 'dislike_alert alert-link' %>
      </span>
      <span class="btn dislikes">
        <%= alert.dislikes.size %>
      </span>
    </span>

    <div class="alert alert-info" role="alert">
      <%= alert.body %>
    </div>

    <% alert.category_list.each_with_index do |tag, i| %>
      <% break if i > 5 %>
      <span class="label label-primary category"><%= tag %></span>
    <% end %>
    <span class="label label-success add-tag">
      <%= link_to "+ Add Categories", add_tag_alert_path(alert), remote: true, class: 'add-tag-link' %>
    </span>

    <div class='add-tag-form hide'>
      <%= form_for alert, url: update_tags_alert_path(alert),  method: :put, remote: true do |f| %>
        <div class="form-group">
          <%= f.label :category_list, "Category (separated by commas)" %><br />
          <%= f.text_field :category_list, autofocus: true, id: "interest_list", class: "form-control"%>
        </div>

        <div class="center-block">
          <%= f.submit t(:update), class: "btn btn-primary" %>
          <%= link_to t(:back), :back, class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </li>
</ul>