config/routes.rb
Konsilo::Application.routes.draw do
  resources :alerts

  root to: "home#index"

  devise_for :user, controllers: {registrations: 'registrations'}do
    get "/login", :to => "devise/sessions#new"
    destroy "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "devise/registrations#new"
  end

  resources :alerts do
    member do
      put "like", to: "alerts#like"
      put "dislike", to: "alerts#dislike"
      get "add_tag", to: "alerts#add_tag"
      put "update_tags", to: "alerts#update_tags"
    end
  end

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  IMPACT = %w[
    High
    Medium
    Low
  ]

  acts_as_taggable_on :categories
  acts_as_votable

  has_many :content_based_scores
  has_many :users, :through => :content_based_scores

  has_many :collaborative_filtering_scores
  has_many :users, :through => :collaborative_filtering_scores

  after_validation :update_ranking_score

  def votes
    self.votes_for
  end

  def likes
    self.get_likes
  end

  def dislikes
    self.get_dislikes
  end

  def rate
    self.likes.size - 2 * self.dislikes.size
  end

  def compute_ranking_score
    avarage_votes = Alert.avarage_votes_size
    avarage_rate = Alert.avarage_rate

    divisor = avarage_votes + self.rate.abs

    return 0 if(divisor == 0 || self.votes.size == 0)

    ((avarage_votes*avarage_rate) + (self.votes.size*self.rate))/(divisor).to_f
  end

  def self.top_ranked(n = 10)
    Alert.limit(n).order("ranking_score desc")
  end

  def self.top_ranked_to(user = nil, n = 10)
    return Alert.top_ranked(n) unless user
    user.get_recommendable_alerts.limit(n).order("ranking_score desc")
  end

  def self.avarage_rate
    alerts = Alert.count
    rates = 0

    Alert.all.each do |alert|
      rates = rates + alert.rate
    end

    rates/alerts.to_f
  end

  def self.avarage_votes_size
    alerts = Alert.count
    return 0 if alerts == 0

    votes = ActsAsVotable::Vote.where(votable_type: "Alert").count

    votes/alerts.to_f
  end

  def self.categorized_as_all(categories)
    Alert.tagged_with(categories, :match_all => true)
  end

  def self.categorized_as_at_least_one(categories)
    Alert.tagged_with(categories, :any => true)
  end

  def self.not_categorized_as(categories)
    Alert.tagged_with(categories, :exclude => true)
  end

  def self.most_popular_categories(limit = 3)
    ActsAsTaggableOn::Tag.most_used(limit)
  end

  private

  def update_ranking_score
    self.ranking_score = self.compute_ranking_score
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy, :like, :dislike, :add_tag, :update_tags]

  respond_to :html

  def index
    @alerts = Alert.all
    respond_with(@alerts)
  end

  def like
    @status = :error

    unless current_user.voted_for? @alert
      current_user.liked @alert
      @status = :created
    end

    respond_to do |format|
      format.js { render layout: false, status: @status }
    end
  end

  def dislike
    @status = :error

    unless current_user.voted_for? @alert
      current_user.disliked @alert
      @status = :created
    end

    respond_to do |format|
      format.js { render layout: false,  status: @status }
    end
  end

  def update_tags

    @alert.update(alert_params)

    respond_to do |format|
      format.js { render layout: false,  status: @status }
    end
  end

  def add_tag
    respond_to do |format|
      format.js { render layout: false,  status: @status }
    end
  end

  def show
    respond_with(@alert)
  end

  def new
    @alert = Alert.new
    respond_with(@alert)
  end

  def edit
  end

  def create
    @alert = Alert.new(alert_params)
    @alert.save
    respond_with(@alert)
  end

  def update
    @alert.update(alert_params)
    respond_with(@alert)
  end

  def destroy
    @alert.destroy
    respond_with(@alert)
  end

  private
    def set_alert
      @alert = Alert.find(params[:id])
    end

    def alert_params
      params.require(:alert).permit(:impact, :source, :title, :body, :views, :category_list)
    end
end

app/views/alerts/_form.html.erb
<%= form_for(@alert) do |f| %>
  <% if @alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
      <% @alert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :impact %><br>
    <%= f.text_field :impact %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :views %><br>
    <%= f.number_field :views %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alerts/add_tag.js.erb
$('.add-tag-link').on('ajax:success', function(){
  var element = $(this).parent().parent().find('div.add-tag-form')
  element.removeClass("hide");
  element.addClass("show");
});

app/views/alerts/dislike.js.erb
$('.dislike_alert').on('ajax:success', function(){
  dislikes = $(this).parent().parent().find('.dislikes').html('<%= @alert.dislikes.size %>');
});

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render 'form' %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<h1>Listing alerts</h1>

<table>
  <thead>
    <tr>
      <th>Impact</th>
      <th>Source</th>
      <th>Title</th>
      <th>Body</th>
      <th>Views</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= alert.impact %></td>
        <td><%= alert.source %></td>
        <td><%= alert.title %></td>
        <td><%= alert.body %></td>
        <td><%= alert.views %></td>
        <td><%= link_to 'Show', alert %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Destroy', alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alert', new_alert_path %>

app/views/alerts/like.js.erb
$('.like_alert').on('ajax:success', function(){
  dislikes = $(this).parent().parent().find('.likes').html('<%= @alert.likes.size %>');
});

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render 'form' %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Impact:</strong>
  <%= @alert.impact %>
</p>

<p>
  <strong>Source:</strong>
  <%= @alert.source %>
</p>

<p>
  <strong>Title:</strong>
  <%= @alert.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @alert.body %>
</p>

<p>
  <strong>Views:</strong>
  <%= @alert.views %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/update_tags.js.erb
$('.edit_alert').on('ajax:success', function(){
  var element = $(this).parent()
  element.removeClass("show");
  element.addClass("hide");
});